apiVersion: v1
kind: Service
metadata:
  name: radinir-frontend
  labels:
    app: radinir
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: radinir
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radinir-frontend
  labels:
    app: radinir
spec:
  replicas: 2
  selector:
    matchLabels:
      app: radinir
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radinir
        tier: frontend
    spec:
      containers:
      - image: radinir-frontend:0.0.1
        imagePullPolicy: IfNotPresent
        name: radinir-frontend
        ports:
        - containerPort: 3000
