version: "3"
services:
  backend:
    image: "gettingradinir-backend:latest"
    environment:
      - MYSQL_HOST=db
    ports:
      - "8080:8080"
    networks:
      - dblink
  db:
    image: "mariadb:latest"
    environment:
      - MARIADB_USER=springuser
      - MARIADB_PASSWORD=ThePassword
      - MARIADB_ROOT_PASSWORD=ThePassword
      - MARIADB_DATABASE=ir_app_data
    networks:
      - dblink

networks:
  dblink:
